### ISSUE TITLE
Need vertical scrolling solution

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#101]
We can't use browser scrollbars in track divs,  it can cause an unpredictable horizontal shift in divs with visible scrollbar.    Need another solution,  custom scrollbar, up/down arrows,  ???

**Comment by muraveill** [comment]
Even with the scrollbar, there is a "preventDefault" missing somewhere, because the two scrolls are moving at the same time - in opposite directions - on this demo page: http://igv.org/web/examples/bam.html

Up/down arrows are terrible. Wouldn't it work to just keep the scrollbar always visible, so that there is not shift when it (dis)appears ? like a css "overflow-y: scroll;"

**Comment by jrobinso** [comment]
Could you clarify what you mean by "moving at the same time in opposite directions"?  How do you produce that?    The internal scrollbar in the track is totally home-cooked,  for various reasons we could not use css overflow for that.

**Comment by muraveill** [comment]
I see, the external one responds to the scrolls settings of my Mac ("scroll direction: natural"), which scrolls down when I sweep upwards and conversely, while the homemade one does the contrary since it ignores this setting. Anyway they both respond to a scroll event at the same time, which can be annoying.

**Comment by muraveill** [comment]
I see, the external one responds to the scrolls settings of my Mac ("scroll direction: natural"), which scrolls down when I sweep upwards and conversely, while the homemade one does the contrary since it ignores this setting. Anyway they both respond to a scroll event at the same time, which can be annoying.

**Comment by jrobinso** [comment]
OK,  I'll see if some sort of focus rule can be applied, or perhaps the 
internal scroll should ignore this event altogether.

**Comment by jrobinso** [comment]
Track viewport now ignores scroll wheel,  you must grab scrollbar and drag it to scroll.
