### ISSUE TITLE
BED File Plots with no Labels

### ISSUE THREAD

**Issue by Alex-Willenbrink** [igvteam/igv.js#1103]
Hello,

Is there a way to add BED file plots without labels? Currently, this is technically possible if the bed file only uses 3 columns like below:

`
2	21044051	21044071
`

If I want to use more than the first 3 columns in the bed file but keep the plots unlabeled, my first thought would be to create a bed file that looks something like this:

`
2	21044051	21044071	${space_character}	1000	-	21044051	21044071
`

The 4th column where the label should be just has a space character. The problem with trying this approach is that the space isn't taken into consideration. It seems like the algorithm for obtaining the data for the plots just groups together all whitespace characters before finding the value in the next column e.g. "tab-space-tab" would be interpreted as "tab". Thus the column with the space is ignored, which shifts over all the column values over and produces a nonsensical plot with the label for the plot being "1000" in this case.

Is there a hack or a method to get around this?

Thanks,

-Alex

**Comment by jrobinso** [comment]
Per general UCSC convention use a "." for blank columns.

There is not a technical spec for the bed file format, or any UCSC file
format for that matter, but our observation has been that they are
whitespace delimited.   It has been a long time since I tested this
however.    If you find that the empty space works in the UCSC genome
browser let me know.

**Comment by Alex-Willenbrink** [comment]
Sounds good!
