### ISSUE TITLE
support in customising loadTrack()

### ISSUE THREAD

**Issue by martina-g** [igvteam/igv.js#1112]
Hi,
first of all, I hope I'm in the correct place, otherwise I'm sorry.
My goal is to make IGV show genomic records (with mismatches against a reference genome highlighted) obtained by calling the api to my custom file (with no supported format). I've followed the workflow from creating the browser to loading tracks. If I understood it correctly, my custom track shall be of type "alignment". 
1. relatively to software planning, which is the cleanest and easiest approach to fulfil my goal? 
 Is it adding the custom handler for my track directly in TrackFactory()?
For now, I do not need to show any property of the genomic records other than the mismatches. I've taken a look to the BAMTrack() class but it looks more complicated then I need my track to be. 
2. is there any example in the repo that I can follow with the basic info I'd need to show?

Thank you in advance

**Comment by jrobinso** [comment]
Hi,
The easiest solution is probably to use a supported format.   Using custom formats for generic annotations is straightforward, but doing so with an alignment track will be difficult.   In fact there is no explicit support for this.   We might at some point support the text "SAM" format, in which case you could create a custom reader to return SAM records, but we don't currently.

**Comment by martina-g** [comment]
thank you for your answer. When you say "it will be difficult" you mean it would be necessary to invest a lot time (weeks) to get to understand how to modify the code (and implement it ) or that a major change of the library is needed and this is not recommended? 
There is not yet the support for "text" file format, but at some point in the code you shall convert the binary data input to "text" in order to process it in the workflow. I'd be interested in finding these calls to data in BAM and provide an interface to my text data instead.

**Comment by jrobinso** [comment]
I can't estimate effort because I don't know exactly what you want to do,  but weeks would be a reasonable guess.  If I understand you correctly you want to create alignments for the "alignment" track to display from your own custom format.      I don't understand you comment about "converting binary to text in order to process it".

**Comment by martina-g** [comment]
yes, I want to feed the instance
`const alignment = new BamAlignment();
`
with data extracted from my custom file.

>  I don't understand you comment about "converting binary to text in order to process it"

I was not clear indeed! I meant that you need to decode the binary bam file in order to get the `alignment` records. I found the function I was looking for in bamUtils.js
`    decodeBamRecords: function (..)
` 
The following step is to implement a custom `decodeCustomRecords()` and make it feed
`alignment = new BamAlignment();`
with data taken from my file.

Would that be enough for the igv viewer?

**Comment by jrobinso** [comment]
There is no place to implement a "decodeCustomRecords" function, however you are on the right track.  What's needed here, I think, is a means to supply a custom reader for a bam track.  It would work similar to the custom reader for annotation tracks,  see examples/custom-reader.html.   This will require me to add some support, which I'm willing to do but can't get to until later in the month.    In the meantime if you want to hack igv.js to get started look at the file "bam/bamSource.js",  specifically lines 52-68.   You'll see a series of if/else that instantiates a "bamReader" depending on a sourceType flag.   You can actually look at the implementations of those various readers to get an idea of what your custom reader will need to implement.    I think the only required method is
```
BamReader.prototype.readAlignments = async function (chr, bpStart, bpEnd)
```

Your reader can ignore the arguments, or not, and should return an array of alignment objects.  This is all the time I have for now, I am just giving you enough to get started, but you can hack BamSource to use your custom reader rather than one provided.    I suggest you do this by providing an instance of your custom reader class in the config, as in  config.bamReader=myReader, in the same way the customReader.html example does.  Hope this is helpful.

**Comment by martina-g** [comment]
Thank you, this is helpful indeed.
I will let you know next week how soon we'd "need" this customisation, if it compatible with the time necessary to implement it and, most of all, if it is ok to wait for your kind support.

**Comment by jrobinso** [comment]
OK, the only customization I have to do with this approach is modification to bamSource to accept your custom reader.   This is easy and I will do it in any event.  Most of the work here will be on your side to develop your custom reader, but that does not impact igv.js.
