### ISSUE TITLE
FeatureTrack click detection returns too many features

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1239]
In the spliceJunctions.html example, if I click on the last junction in CHD2, the popup contains entries for ~25 junctions, but only 1 of them overlaps the clicked genomic location:

![image](https://user-images.githubusercontent.com/6240170/101111467-37fced80-35a9-11eb-9dee-7b7df2736611.png)

**Comment by jrobinso** [comment]
The bug is in "merged track", which I will fix,  however there will still be a problem because we are relying on the generic "feature track" hit test for the click.   I don't see a hit test on the actual arc anywhere,  which will be necessary to distinguish between overlapping arcs.   However first I will fix the main bug here,  it looks like merged track does not do any hit testing at all.

**Comment by bw2** [comment]
thanks. I think the generic interval boundary test is good enough since there are 1 to a handful of arcs overlapping a region in most cases (especially after filtering using the other junction track options). Detecting down to the specific arc seems not worth the effort and extra compute cost.

**Comment by jrobinso** [comment]
You tend to pickup a lot of "wig track" intervals if zoomed out, nothing we
can do about that.  To make the junctions appear first have the junction
track first in the merged track list.
