### ISSUE TITLE
Loading track from url fails, though works locally

### ISSUE THREAD

**Issue by noamshoresh** [igvteam/igv.js#129]
There is a tss table here:
http://www.broadinstitute.org/epigenomics/dataportal/cursor/tssTable.hg19
I have it also as a local file.

I can load it as a track from the local file, but not if I use the url.

**Comment by jrobinso** [comment]
I'll look into it.  Is there are good reason that file doesn't have a 
".bed" extension?

**Comment by jrobinso** [comment]
The reason is the CORS headers are not being set on this file.   We had 
a workaround for this that used to work,  I'll look into why it isn't,  
but we shouldn't need work arounds for our own (Broad hosted) files.   
Could who ever is in charge of this portal add the 
Access-Control-Allow-Origin header?   They can contact me if they aren't 
sure how to do this.

If the file is served from an apache server the headers can be added 
with a .htaccess file,   I can provide one.

Jim


XMLHttpRequest cannot load 
http://www.broadinstitute.org/epigenomics/dataportal/cursor/tssTable.hg19. 
No 'Access-Control-Allow-Origin' header is present on the requested 
resource. Origin 'http://igv.org' is therefore not allowed access.

**Comment by jrobinso** [comment]
I'll add, the "workaround" is ineffecient and a last-resort for external 
users, not our own use,  so let's fix the CORs problem.
