### ISSUE TITLE
Reference with multiple sequences per chromosome

### ISSUE THREAD

**Issue by dennishendriksen** [igvteam/igv.js#1301]
First of all thank you very much for creating and maintaining the Integrative Genomics Viewer. We are very happy after having migrated from the Dalliance genome browser to IGV.

We are embedding the genome browser in a standalone report (somewhat similar to [igv-reports](https://github.com/igvteam/igv-reports)) using data URIs to load reference, variant and alignment data. The reference and alignment data only cover regions surrounding the variants. A reference might look like this:

```
>1:10042038-10043038
CAGCC etc.
>1:17348715-17349719
AGAGC etc.
>1:17354594-17355675
AATCC etc.
```

Works like a charm when performing:
```
browser.search('1:17355155')
```
![igv_self_contained_fasta0](https://user-images.githubusercontent.com/2477186/113107138-dae61100-9203-11eb-9fb4-035e87df4a74.png)

But fails to show reference nucleotides when performing:
```
browser.search('1:10042518')
```
![igv_self_contained_fasta1](https://user-images.githubusercontent.com/2477186/113107492-4a5c0080-9204-11eb-94d8-1cd5fef2f213.png)

In both cases the dropdown displays duplicate entries, could this be a related issue?
Selecting the 'all' dropdown entry results in error `Uncaught (in promise) Error: Unrecognized locus all`

Loading the same fasta file in the IGV desktop application look like:
![igv_self_contained_fasta2](https://user-images.githubusercontent.com/2477186/113107761-9313b980-9204-11eb-9ca0-4c3c24842692.png)
Selecting the 'All' dropdown entry doesn't result in an error.

Diving into the codebase I was wondering if the issue could be caused by:
https://github.com/igvteam/igv.js/blob/v2.7.9/js/genome/fasta.js#L127
which appears to expect one sequence per chromosome.

Unfortunately defining one sequence per chromosome won't work for our use case because of the potentially huge amount of additional data that needs to be embedded.

**Comment by jrobinso** [comment]
Yes, 1 sequence per chromosome is a requirement, in fact that is what a "chromosome" is.   To make this work you will need to change your model, as igv-reports does, so that each of your slices is envisioned as a new assembly (new genome) with a single sequence.     You can save this assembly and all the related tracks as a session,  then add a menu external to igv.js to select the "session".    In igv-reports the sessions are compressed and stored in the page itself, but this isn't neccessary,  you can save the sessions in the standard session json format.

**Comment by dennishendriksen** [comment]
Thanks for the quick response, I'll look into updating my model.

**Comment by jrobinso** [comment]
@dennishendriksen No problem.   If you have further questions post them here.    You will use [browser.loadSession](https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#loadsessionurl) to load your session json.   This method can also take a dataURI if needed, which igv-reports produces, or you can just use plain text session json files.    If you are working in javascript instead of python look at the method ```Browser.compressedSession``` in browser.js.    But again compressing the session json isn't required.
