### ISSUE TITLE
Show soft clipping in bam track

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#146]

**Comment by bw2** [comment]
This would be really useful for looking at raw reads.

**Comment by axel-bernal** [comment]
+1

**Comment by Lenbok** [comment]
You can already set View -> Preferences -> Alignments -> "Show soft-clipped bases".

Do you mean something different to this?

**Comment by cristynkells** [comment]
Agree with bw2.  Is soft clipping on the igv.js roadmap?

**Comment by will-NYGC** [comment]
+1

**Comment by gnarzisi** [comment]
+1

**Comment by fangxiaolan** [comment]
+1

**Comment by hmgeiger** [comment]
+1

**Comment by MarWoes** [comment]
+1

**Comment by ltnetcase** [comment]
+1

**Comment by bw2** [comment]
would you be interested in someone contributing a PR for this?

**Comment by jrobinso** [comment]
Yes, but let me look at it, to provide guidance at least.   This issue has
a lot of up votes so we should do it.   However,  no one has really
specified what they want to see.   The way we show soft clipping in IGV
desktop is really misleading,  the reads are just extended as if the soft
clipped portions had been aligned.   They really should not be displayed
against the genome reference.    In some cases, you just want to know the
reads are clipped.    Forgetting temporarily how this is handled in IGV
desktop,   how ideally would you want to see the soft clips?

**Comment by bw2** [comment]
I'll gather some ideas.

**Comment by bw2** [comment]
This just came up again for a variant someone is evaluating in seqr so I shared Jim's criticism of desktop IGV visualizations above in a seqr channel and got this feedback:

"I like to see that the reads are clipped. I don’t interpret it as the soft clipped part aligns against the reference (all the color convinces me it doesn’t align but that something is going on here)" (Anne).
"I don’t find it misleading - it’s a nice visual indicator of total misalignment" (Daniel). 

The only thing I'd add is - if this easy to do, it would be nice if the popup from clicking on a read showed the soft-clipped bases as text so that you could copy-paste it into blat.

**Comment by jrobinso** [comment]
OK, thanks for the feedback, yes I will implement soft-clipped in igv.js as it is in desktop.    I've tagged soft-clipping for release 2.1 of igv.js.   

WRT the popup text, of you right-click an alignment in desktop one of the menu items is "blat read sequence" ,   there is also an item "copy read sequence".     This refers to the read sequence, not the aligned sequence,  so it will include the soft clips.   @bw2 could you pass this on to Anne?   Or perhaps she is requesting the same feature in igv.js?

**Comment by bw2** [comment]
making it easy to blat only the soft-clipped sequence from igv.js is my own request (for resolving breakpoints, for example - perhaps by including the full sequence as text, with soft clipped bases in a different color).
Also, at this stage, do you prefer doing this internally, or would you be interested in code contributions?

**Comment by jrobinso** [comment]
Oh sorry, I misinterpreted that.  Is the soft-clip blat a request for desktop, igv.js, or (probably) both.  If for desktop could you open an issue there?

I'm always interested in code contributions.  Its probably helpful to have a discussion on approach first.  For this issue I would have to look at the code a bit, which I'm happy to do.  The tricky thing about soft clips is accounting for it when packing the alignments, otherwise its trivial to just draw it.  So for packing purposes the extent (start and end) of the alignment now includes soft clips.   Also, the alignment can and will have negative genomic coordinates at the beginning of a chromosome.   This is not an esoteric case because many people using this option are doing assemblies.   Generally its assumed negative coordinates don't exist so things will break here and there.    

Of course its possible fresh eyes would take a different approach that would not have this problem, that's just how it was done in IGV desktop.   Just typing this I think there is probably a better way to handle packing,  perhaps just a new optional field  "packingStart" and "packingEnd"  or "visualStart" and "visualEnd" that default to start & end,  but are modified when soft-clips are on.   Packing would use those properties,  everything else is unchanged.   So disregard the previous paragraph.

**Comment by bw2** [comment]
It's for igv.js, as that's now our primary UI for variant review (AFAIK soft-clipping is currently the only feature for which we go back to desktop IGV on small variants). 
Thanks for the pointers on the challenges. I will post again if/when I or someone here gets a chance to look at the code in detail.

**Comment by jrobinso** [comment]
OK,  I might get to it before you do.

**Comment by jrobinso** [comment]
Woa, sorry, I should have closed this.    CRAM is implemented to, in case you missed that.
