### ISSUE TITLE
How to Sort seg-track by sample name

### ISSUE THREAD

**Issue by arpanda** [igvteam/igv.js#1480]
I am trying to sort samples by samples name for `Segmented Copy Number Track` and was following the https://github.com/igvteam/igv.js/wiki/Seg-Track#segmented-copy-number-track link as a guide. but I could not find any documentation for that. So, is it possible ? if yes, could you please guide.

Thanks
Arijit

**Comment by jrobinso** [comment]
Sorry thats not possible currently.    You can leave this open as a request.

**Comment by onursumer** [comment]
Hi @jrobinso, we are experiencing a similar problem in cBioPortal. We would like to make sure that the mutation track is sorted by a custom sample order we define. For example we would like to make sure that first row in the example below belongs to `(1) P04_Pri` instead of `(2) P04_Rec1`.

<img width="1124" alt="mutation_track_sample_order" src="https://user-images.githubusercontent.com/3604198/166062886-4842605a-e83a-41cf-b2be-6bd6d9fa87e8.png">

I tried to pre-sort the mutation features by the same sample order, but igv.js sometimes breaks that order when applying its own sort logic. 

Do you know if there is an easy fix for this? This is the only thing holding us right now from releasing the new feature. Here is the preview link for the sample list above: https://deploy-preview-4188--cbioportalfrontend.netlify.app/patient?caseId=P04&studyId=lgg_ucsf_2014

**Comment by jrobinso** [comment]
You can specify the sample explicitly in the order you want to see them and it should maintain that.   Apologies this doesn't seem to be documented, I think it was added for cBio.  The config property is "samples", which should take an array of sample names.  If this is supplied only those samples will be shown, in the order specified.   If you are already using that parameter and it isn't working that would be a bug.

**Comment by onursumer** [comment]
@jrobinso Thank you! I might have overlooked the `samples` property. It works as desired now.

**Comment by jrobinso** [comment]
It should be documented.  I added an example to  "examples/copyNumber.html".

**Comment by jrobinso** [comment]
@arpanda Is this what you meant by "sort"?  I interpreted this to mean dynamically sort, but if you just want to specify a set order you can use the "samples" property.   Here is an example

```
                    {
                        name: "Explicit Samples",
                        type: "seg",
                        format: "seg",
                        samples: [
                            "TCGA-06-0168-01A-02D-0236-01",
                            "TCGA-02-0115-01A-01D-0193-01",
                            "TCGA-02-2485-01A-01D-0784-01",
                            "TCGA-06-0151-01A-01D-0236-01"],
                        url: "https://s3.amazonaws.com/igv.org.demo/GBM-TP.seg.gz",
                    }
```

**Comment by arpanda** [comment]
This will work. Thanks
