### ISSUE TITLE
Paired Reads Horizontal Center Line 

### ISSUE THREAD

**Issue by DustBytes** [igvteam/igv.js#1577]
Dear @turner @jrobinso 

When we do "view as pairs" on desktop there is faint horizontal line in the read. That helps to quickly differentiate the paired and unpaired reads.
I can't see that line in igv.js.

The color of the horizontal line changes according to the coloring of the reads.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/9694405/213623875-f330e6a5-d81a-4d87-a1f5-5c958fe06a64.png">

**Comment by jrobinso** [comment]
I don't know where that line is coming from,  I don't see it in any of my data.   Its not intentional.   Actually that data looks like your pairs are overlapping, and the line is an artifact.   This is what view-as-pairs typically looks like

<img width="807" alt="Screen Shot 2023-01-19 at 10 42 20 PM" src="https://user-images.githubusercontent.com/933148/213633810-46ce240d-c095-4449-bf96-70339871a3f9.png">

**Comment by DustBytes** [comment]
Dear @jrobinso 

Yes the line is coming during overlapping.
We can see the overlap with color change.
On desktop IGV the line is viisble.
We can work without this.

Please close this.

Thank You
