### ISSUE TITLE
How to upload tracks from client side

### ISSUE THREAD

**Issue by carlosribas** [igvteam/igv.js#1638]
I would like to allow user to upload tracks, something similar to what igv.org/app does. I don't need to persist the content of the file - if the user closes the page then the content is lost and that is fine.

I tried to use FileReader: 

```
const reader = new FileReader();
reader.readAsDataURL(event.target.files[0]);
reader.onload = event => {
  setFile(event.target.result);
};
```

and that will give me a data URI as described here: https://github.com/igvteam/igv.js/wiki/Data-URIs. However, I'm getting "invalid distance too far back" error when I try to load the track. Is this supposed to work? I'm using IGV 2.15.5 in a React app. Any feedback is welcome. Thanks!

**Comment by jrobinso** [comment]
Hi,  I'm not sure what you are trying to do from the snippet,  there is no igv.js code there.   What does "setFile" do?   

You can pass a data URI string to any igv.js track config in the "url" field, as well as a javascript `File` object.   Since you already have a `File` (event.target.files[0]) the simplest thing to do would be to just pass that to igv.js in the `url` property of the tack config.  

There are examples of using dataURIs in the dev/datauri folder.

BTW everything is on the client side,  there is no server involved here so no upload.

**Comment by carlosribas** [comment]
Thank you for your prompt reply!

Sorry for not adding the IGV code. setFile is a state variable that takes a data URI, so I'm just creating a track with:
```
const [file, setFile] = useState();
...
const userTrack = useMemo(() =>{
    return {
      name: "User track",
      type: "annotation",
      format: "gff",
      displayMode: "expanded",
      order: 1,
      url: file,
    }
  }, [file])
...
browser.loadTrack(userTrack); 
```

Well, for some reason a data URI isn't working, but as you suggested, I just tested it with a `File` and it worked. I will close this issue as this solves my problem :)

Thank you for your help.

**Comment by jrobinso** [comment]
If you capture the value of "file" for a dataURI and post the string here I would be interested in understanding why it is not working.

**Comment by carlosribas** [comment]
Hi. I think there was something wrong with the file I was using. I did a test now with another file to generate a dataURI and it worked. Sorry about that and thanks for your help.
