### ISSUE TITLE
CORS Firefox

### ISSUE THREAD

**Issue by thedam** [igvteam/igv.js#1644]
Hey, my .bams are served from another server than IGVjs app is running. Everything works on Edge or Chrome, but on Firefox I get CORS errors:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.21.152:82/xxx/xxx/xxx/my.bam. (Reason: CORS preflight response did not succeed). Status code: 405.
`
![image](https://github.com/igvteam/igv.js/assets/634773/061166a9-35c8-413d-b7da-e3bc1b83e4b9)

ps. I use Django, Nginx, Gunicorn + Vue2 (with igv 2.15.7) on ...67:82 server
the bams are served by Nginx from ...152:82 server

why it's happing? I believe some headers have to be encoded in igv.js code as it works on another browsers...

**Comment by jrobinso** [comment]
I think the error message is pretty clear from the client browser point of view, the server is returning a 405 error for the "preflight" request.    So the question is why?  Searching "cors preflight 405 error Nginx firefox" turns up quite a few hits, including this one

In case it might help others: For me it turned out to be a certificate issue. Chrome automatically uses certificates added to Windows. FireFox does not. So had to import our self-signed dev server certificate into FireFox, and then the CORS worked again. 🙂 – 
[Svish](https://stackoverflow.com/users/39321/svish)
 [Aug 12, 2020 at 8:07](https://stackoverflow.com/questions/24514666/why-is-this-cors-request-failing-only-in-firefox#comment112058664_24514666)

Firefox works fine for me with igv.js and CORS, but I am on a Mac.

The CORS handshakes happen before igv.js sees anything from the server, and the PREFLIGHT request and headers are done by the browser as well.   So igv.js itself is not involved in CORS.
