### ISSUE TITLE
In the Genes Track, The Exon should be -1 position but it look like -2.

### ISSUE THREAD

**Issue by TamarOr** [igvteam/igv.js#1753]
sorry for the delay in our response:(
we are prepared to communicate with you.
any information you need!!

We use these 4 files.
b37_cytoband.txt
cytoBandIdeo.txt
human_g1k_v37_decoy.fasta
human_g1k_v37_decoy.fasta.fai
In the code, we saw that start is correct but start+1 is displayed in the UI.

_Originally posted by @TamarOr in https://github.com/igvteam/igv.js/issues/1746#issuecomment-1903480034_

**Comment by jrobinso** [comment]
Its best not to start new issues, please add comments in the existing issue.   In the original screenshot you have more files than that, there is a file for GENES and an alignment file.  The problem is with the file you are using for the GENESE track, its coordinates are off by 1.  this is not an igv.js issue, it is a problem with your file.
