### ISSUE TITLE
"Goto" bugs

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#180]
This doesn't work
1:861,305

Also, this doesn't work-- it doesn't enforce minimum window size of 40 bp or so
1:861,305-861,306

**Comment by jdelafon** [comment]
This does not work either:
chr17:1-1000000000

It changes automatically to 
chr17:-,918,804,789--,837,609,580

instead of clipping.
Choosing other ranges produces other "random" intervals:
chr17:-99,018,804,780--98,937,609,571
chr17:-1,234,486,694,790--1,234,405,499,581
chr17:-42,261,579-38,933,630

In the latter case, it gets displayed even if the first coordinate is negative, half of the range being outside the genome.

**Comment by jrobinso** [comment]
The first range is not a real genomic range, what assembly has a length == 1000000000?   This should produce an error, message, or just clip, I agree.   Is that what you are reporting?

I don't follow the rest of your post at all, what do you mean "choosing other ranges"?

**Comment by jdelafon** [comment]
Yes. It is the first thing I did naturally to get the whole chromosomal range, without knowing the chromosome length (I know, "chr17" alone would have worked). Also one could enter one more digit by accident, and not understand what one's seeing.

By "other ranges", I meant queries like "chr17:99-1234576899", randomly. They produce negative ranges without raising an error.

I think it should just clip left and right.

**Comment by jrobinso** [comment]
I agree, but really this is a different issue than #180.

**Comment by jdelafon** [comment]
Should I open a new issue ?

**Comment by jrobinso** [comment]
It would be helpful, just copy / paste the original report.  I'll remember the rest.

**Comment by jrobinso** [comment]
@turner I'm restating the original bug as this issue got side-tracked.   

This doesn't work
1:861,305

Also, this doesn't work-- it doesn't enforce minimum window size of 40 bp or so
1:861,305-861,306

**Comment by turner** [comment]
Closed with commit da857fa0
