### ISSUE TITLE
The YC tag in bam does not work and does not display the corresponding color

### ISSUE THREAD

**Issue by windforclouds** [igvteam/igv.js#1811]
hello!
     I added YC tags to specific reads in bam to display different colors, which can be displayed according to the tag in igv software, but there is no response after selecting YC tag in IGV-Reports. Is this not supported yet?
![image](https://github.com/igvteam/igv-reports/assets/46742903/1d7bd060-38cf-4afb-9bfb-ba2b5081086d)

**Comment by windforclouds** [comment]
ok, I have sent the html report to igv-team@broadinstitute.org

**Comment by jrobinso** [comment]
Thanks, there does seem to be a problem with igv.js.   I will update here when there is a fix.

**Comment by jrobinso** [comment]
Sorry for the delay.  The issue is encoding of color,  igv expects a UCSC style color string encoding the red, green, and blue values as integers in the range 0-255,  e.g. ```255,0,0```.   It does not recognized hexadecimal numbers as colors.   The YC tag itself is not reserved, and is used by various tools for various things besides color,  so values not in the recognized form are treated as just arbitrary values.

I will look into allowing hexadecimal color encoding as a special case, but that is where the issue lies with the current release.

**Comment by jrobinso** [comment]
Sorry for the delay.   I looked into this, the current version of igv.js recognizes "r,g,b" strings for the YC color value, other color representations, such as the hexadecimal strings your file uses, are not recognized as colors.   I generalized this for the next release so hex numbers will be recognized.

**Comment by windforclouds** [comment]
Thanks a lot!
