### ISSUE TITLE
IGV in a secondary tab does not show initially 

### ISSUE THREAD

**Issue by VidJa** [igvteam/igv.js#1856]
I'm not sure if this a bug or a feature, but when I integrated IGV in our site I noticed the following behavior:

With bootstrap 4:
- I'm displaying data on a sample in the primary tab of a tabbed view.
- The second tab contains the IGV view for that sample, linking to a VCF and bam tracks for that sample.

when switching to the IGV tab:
The configured IGV instance loads, but the tracks do not display, until I click on the search icon or select a different chromosome.
After that, I can switch tabs as usual and when I switch back to the IGV tab it shows as expected.

I made a little codepen to show the behaviour. This happens both on Firefox (128.0.3) and Chrome  126.0.6478.185 on my Macbook M1

https://codepen.io/VidJa-Hunter/pen/yLdMoaY

**Comment by efgstone** [comment]
I had a similar issue when using modals. I needed to add an on-show event to my javascript to get igv .search() to perform automatically without having to click the magnifying glass. I'm not sure what the underlying issue is, but I assumed the hidden parts of the page (modals, or tabs in your case) are not fully rendered in the background.

I added an on show event for your tab in the codepen and this has fixed the issue in that IGV not loads the correct position when you click the tab. You might want have IGV loaded in the tab as you already have done, but then use the on-show event to search a particular locus. I think this would make things a little smoother.

```  
$(document).on('shown.bs.tab', 'a[data-toggle="tab"]', function (e) {
            igv.createBrowser(igvDiv, options)
                .then(function (browser) {
                    igv.browser = browser;
                    console.log("Created IGV browser");
                })
}) 
```

**Comment by jrobinso** [comment]
Have you tried calling "browser.visibilitychange()"?  

```
https://igv.org/doc/igvjs/#Browser-API/#visibilitychange
```

See also https://igv.org/web/release/3.0.1/examples/tabs.html

**Comment by VidJa** [comment]
I had to use a combination of both to get it working on my page:
```
// inside the page's $(document).ready function

var browser = igv.createBrowser(igvDiv, igvOptions).
              then(function (browser) {
                  igv.browser = browser;
                  console.log("Created IGV browser");
              });
 ```     

```$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
          igv.visibilityChange();// activated tab
      });
```
bu I have to admit, my javascript knowledge is very limited
