### ISSUE TITLE
Can't show bam reads when num is large

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#234]
Hi,
The reads are all disappeared when I set maxRows larger than 2336 in my situtation, though the popupmenu shows well when I click an invisible base. The coverage is about 2500.

**Comment by jrobinso** [comment]
Its possible this is too large for a canvas object, or the underlying 
div.   There is a limit, 2500 rows would be about 50,000+ pixels high. 
    Are there any errors in the console?  Try "squishing" the track to 
see if the alignments appear.

**Comment by jrobinso** [comment]
The maximum height of a canvas is  32,767 on Chrome and Firefox.   The default height of an alignment row is 14,  with 55 pixels reserved for the coverage, so that would imply a max row count of 2338.   I will add some documentation about the limit.   You can squeeze more rows in by reducing the height of each row of the track,  the property is alignmentRowHeight.

Did you also disable downsampling (samplingDepth property)?

Its unusual to need to see every individual alignment in a deep coverage bam,  that's why we downsample.   Could you elaborate on the need to do this?  Performance is likely to be poor.

**Comment by jrobinso** [comment]
Recent thread on the topic: http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

**Comment by desnar** [comment]
Thanks.
It just happened when I tried to check the results occassionaly.
