### ISSUE TITLE
"goto" whole chromosome doesn't work

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#248]
Typing chr1 in the search box doesn't work, it should jump to a whole chromosome view.

**Comment by turner** [comment]
Fixed with commit fb66ed43

**Comment by blajoie** [comment]
Howdy! 
It looks like this change broke click-and-goto using the karyo plots.
<end> now comes through as NaN.

This block of code needs to be added back into browser.js.

 -        this.referenceFrame.bpPerPixel = (end - start) / (viewportWidthPixel);
 +         
 +        // If end is undefined,  interpret start as the new center, otherwise compute scale.
 +        if (!end) {
 +            w = Math.round(viewportWidthPixel * this.referenceFrame.bpPerPixel / 2);
 +            start = Math.max(0, start - w);
 +        }
 +        else {
 +            this.referenceFrame.bpPerPixel = (end - start) / (viewportWidthPixel);
 +        }
