### ISSUE TITLE
Allocation Size Overflow

### ISSUE THREAD

**Issue by muelleralex** [igvteam/igv.js#251]
Hi, 

I am currently running IVG.js off of a locally hosted Apache web server (via XAMPP), and I am attempting to add a variants track from a VCF from 1000 genomes (the VCF and its index are also hosted locally). Unfortunately I keep getting an "allocation size overflow" error and don't know how to fix it. Any tips?

Thanks!

**Comment by jrobinso** [comment]
I need more details, or better an html file that reproduces it.   If you attach a test html file and point me to the VCFs you are using I can download them myself and setup a test here.

**Comment by muelleralex** [comment]
When I use a vcf.gz file for the url and a vcf.gz.tbi for the index file I get this error in the console: "RangeError: argument 1 accesses an index that is out of range", and a error window pops up that says either "InternalError: size and count too large" or "out of memory".

When I use an uncompressed vcf file and a vcf.idx file for the index I get the allocation size overflow error. 

Here is a link to the VCFs I am using: http://users.rcc.uchicago.edu/~ajmueller/ggv_vcf/

Here's a text file with the html I was using: [index.txt](https://github.com/igvteam/igv.js/files/443835/index.txt)

**Comment by jrobinso** [comment]
Could you try lowercase for the format,  or leave the format off
altogether.   i.e. format: "vcf",

It doesn't suprise me that the ".idx" index does not work,  stick with
tabix  (.gz / .gz.tbi) for files this size.

**Comment by muelleralex** [comment]
I'll avoid the ".idx" and stick with tabix. I removed the format, but I am still encountering the RangeError.

Here is the specific error that is outputted to the console in Firefox:

"RangeError: argument 1 accesses an index that is out of range
Stack trace:
igv.BinaryParser.prototype.getString@https://igv.org/web/release/1.0.1/igv-1.0.1.js:4476:21
readHeader@https://igv.org/web/release/1.0.1/igv-1.0.1.js:10208:35
igv.loadTribbleIndex/igv</<@https://igv.org/web/release/1.0.1/igv-1.0.1.js:10166:25"

**Comment by jrobinso** [comment]
OK,  it will take some time to download these.  If you can point me to the
originals at the 1KG site I can load them directly without downloading.

**Comment by jrobinso** [comment]
I found them at the 1KG site.   Those URLs work fine,  try substituting these for what you have, then  jump to the gene "myc"
[1kg-vcf.html.txt](https://github.com/igvteam/igv.js/files/444037/1kg-vcf.html.txt)
 

https://s3.amazonaws.com/1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz

https://s3.amazonaws.com/1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi

Or load the attached html.   I suspect the problem is with your server, does it support range byte requests?  If you open developer tools you can monitor network requests & response which should give a clue.

**Comment by jrobinso** [comment]
I've also loaded the html file to 
http://igv.org/web/examples/1kg-vcf.html

**Comment by jrobinso** [comment]
Is this resolved?  I can't find any problem in the igv client itself.

**Comment by muelleralex** [comment]
Yes, sorry. The issue appears to be with the way I was storing the vcf files. Thank you so much!
