### ISSUE TITLE
wig/bedGraph files not displayed when using gff annotation

### ISSUE THREAD

**Issue by zoecastillo** [igvteam/igv.js#266]
We'd like to use igv.js for quantitative data in either wig or bedGraph format having both the data and genomes on our own server. This works well as long as no annotation is added (though it would be great if lineplots were an option). However, whenever a gff-based annotation file is also loaded, the wig/bedGraph data is no longer displayed.

This seems to be caused by the wrong Parser being used to load in the wig/bedGraph data (it gets overwritten by the gff one).

**Comment by jrobinso** [comment]
I commented on the pull request,  but I cannot see how the parser would be "overwritten".    Each call to the enclosing function would have its own scope.

**Comment by jrobinso** [comment]
Ahh, after much back and forth I got it.   The problem was "parser" was not defined in the enclosing function scope,  so it had window scope.  So all FeatureFileReader instances were sharing the same parser.   You fix worked by switching it just-in-time.  I've pushed an alternative fix that doesn't use a parser variable at all. 

Thanks for reporting this.

**Comment by zoecastillo** [comment]
Thanks for the quick fix!

**Comment by jrobinso** [comment]
Thanks for the report!   That was such an interesting and subtle bug,  the
real problem was the lack of a "var" declaration in front of the "parser"
variable, thus making it effectively a global.   A good question for a test.
