### ISSUE TITLE
Loading local files with an index without a data server.

### ISSUE THREAD

**Issue by ThomasCarroll** [igvteam/igv.js#310]
hi,

Thank you for a great piece of software!
I had previously developed a [bioconductor package to build HTML reports for IGV using R](https://www.bioconductor.org/packages/release/bioc/html/tracktables.html)

I would love to be able to extend to include IGV.js. 
Is there a way to display local files in IGV.js without using data server (As with IGV java version.) ?

thanks,

tom

**Comment by jrobinso** [comment]
Thanks for the pointer to your bioconductor package, it looks nice.

WRT local files, not at this time.   I assume you mean loading a file with
a local file path.    We plan to do it, and have done it with other
projects,  but as far as I know it requires user interaction with a
dialog.  I don't think there is any way to feed paths to javascript via a
script, for example, and have them load due to browser security.

This is not a topic I am an expert on,  suggestions are welcome.

**Comment by ThomasCarroll** [comment]
hi Jim,

Thank you the clarification. Yes, that was what we were hoping but figured security maybe the issue.
We will implement igv.js version using data servers for now in the package.

Thank you again for all your and the team's work on this great project.

best,

tom

**Comment by jrobinso** [comment]
If you find some (legit) way around the security issues please re-open the
issue.   File URLs won't work in general due to mixed-protocol
restrictions.

**Comment by ThomasCarroll** [comment]
Thanks, I will do.
