### ISSUE TITLE
Load local index bam files

### ISSUE THREAD

**Issue by xtmgah** [igvteam/igv.js#314]
Hello: 

Is there any way to load local index bam files in the html? For example, in the example file:  bam.html, i want to replace:
url:'https://data.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam'

with my local bam file: 

url: '/Users/zhangt8/Dropbox/Everyday_Syn/Kidney_BAM_IGV/test.bam'

But it was not working... any suggestion here? Thanks.

**Comment by jrobinso** [comment]
Yes, of course, it is by far the most common way to load a bam file.   You
will need to provide more information,  what is not working?

**Comment by jrobinso** [comment]
Sorry, ignore my previous comment (deleted).  I develop and support both IGV desktop and igv.js, the answer applied to IGV desktop.  This is not possible with igv.js,  you cannot load files from a local file path.   What you supplied is not a URL, and even if it were a file:// url it would not be allowed due to mixed-protocol restrictions among other problems.
