### ISSUE TITLE
Automatic scaling of eQTL tracks

### ISSUE THREAD

**Issue by francois-a** [igvteam/igv.js#329]
All eQTL tracks currently use the same scale, and p-values beyond the maximum are capped, which distorts the data. Would it be possible to modify the default behavior, such that each track scales independently? The dynamic range could be determined using a percentile of p-values to avoid extreme outlier effects (these would be still be capped, but could be shown in another color or marker to indicate this).

Thanks!

**Comment by jrobinso** [comment]
@francois-a Apologies for the long delay in responding.   Is this topic still of interest?

**Comment by francois-a** [comment]
@jrobinso Yes, thanks!

**Comment by jrobinso** [comment]
OK,  I've tagged it for the 1.1 release,  which we are working to finish now.

A followup question -- are you using the eQTL web service,  or the file format?    And what version of igv.js are you using?  I ask because the eQTL track was created specifically for the gtex portal and the api never published in our doc,  to make it public and supported I need to figure out what you are using.   I wasn't aware until reviewing old issues that anyone other than gtex was using this.

**Comment by francois-a** [comment]
Thanks! This is for the GTEx Portal -- I'll ask someone from the team to comment.

**Comment by jrobinso** [comment]
Oh, sorry I didn't make the connection.

**Comment by jrobinso** [comment]
Also, as this is gtex no answer needed re what you are using.  

Can I take this then as an official request from GTEx,  or are you just asking if its possible?   Yes its (probably) possible, but I need a bit more precision on what you want.

Would scaling be based on the range of values that are in view?  This can be confusing as the scale would change based on what locus you are viewing.   So if you are in a region with uniformly low p values they are going to get autoscaled so that many of them look significant when they are not.  

If instead, you mean to scale based on the range of p-values across the whole genome that will need to be done offline.   The igv track scale could then be set in the track configuration explicitly, independently for each track.   For this you don't need any additional igv updates, the capability is there now to explicitly set the scale.

**Comment by khadley** [comment]
@francois-a Do you know if we want the track scaling to be only for the window that's being viewed or for the entire genome?

We could implement it for the whole genome first and then later (or soon since 1.1 is coming out) change it to scale according to the window.

Or we could figure out the case when we'd want the track to scale across the whole genome and the case when we'd want the track to scale for the viewing window and have those render the right option at the appropriate times.

**Comment by francois-a** [comment]
Yes, please consider this a request for the portal. Sorry if that was ambiguous. 

It's fine if done in the window (I don't think genome-wide would work--the presence of loci with very small p-values will make everything else look insignificant). Since significance is not determined on an absolute scale, users will have to check the y-axis range in any case.

**Comment by jrobinso** [comment]
OK,  got it.   Note that "region in view" in igv.js includes a flanking region +/- the current window width.   That will be used to autoscale.   There is no easy way to scale to the precise region in view.

@khadley could you check the track configs in dev/gtex.html and edit them if they are out of date?  Send me a pull request.   Or you can just attach the modified gtex.html in an email.

**Comment by jrobinso** [comment]
@francois-a I've implemented this and and am trying to test it but am getting a 502 "bad gateway" error from your server.   @khadley here is the URL that is giving the error,  could you let me know when its fixed and I am able to test?  Thanks.  https://dev.gtexportal.org/rest/v1/association/singleTissueEqtlByLocation?chromosome=1&start=7355127&end=10141158&tissueName=Brain_Cerebellar_Hemisphere
