### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by jdelafon** [igvteam/igv.js#360]
If I forget to add the "type" argument in Tracks options, instead of "Invalid track type", I get 

> TypeError: Cannot read property 'toLowerCase' of undefined

because of this:

    igv.Browser.prototype.loadTrack = function (config) {
        ...
        switch (config.type.toLowerCase()) { ... }

If I comment the "genome" argument in Browser options, I get

> igv-1.0.7.js:15084 Uncaught TypeError: Cannot read property '$dialogLabel' of undefined

etc.

**Comment by jrobinso** [comment]
That looks like quite an old version of igv.js,  I don't see it in the
current code.

**Comment by jrobinso** [comment]
Looking at the 1.0.7 code I think you would only incur the config.type error if you are using an unrecognized file extension.   In that case "type" is required.   I will patch the code to give a more explicit error message.   Also either "genome" for a reference object is required,  you can't just comment it out.

**Comment by jrobinso** [comment]
The type problem is fixed in 1.0.8,  fixed in the sense that you will get an error message.  If you reach this block of code it means the type could not be determined from the file extension.  The "genome" argument has been deprecated for several releases, it was a mistake to have that in the examples (corrected).    Its replacement, the "reference" object, is required.
