### ISSUE TITLE
Missing documentation for events

### ISSUE THREAD

**Issue by vrockai** [igvteam/igv.js#362]
By traversing the source code, I've found the IGV.js is firing a lots of useful events:
* `trackremoved`
* `locuschange`
* `trackdrag`
* `trackdragend`
* `trackclick`

Those are not documented anywhere. Since I'm using some of them already in my app, I want to make sure the documentation is just missing and I can count on them in next versions, too.

**Comment by jrobinso** [comment]
The event feature is not officially released, its experimental and the implementation could change.  Major changes are unlikely, however.   These will be released and documented in v 1.1.    Once released we try to only make changes in a backward-compatible manner.

**Comment by odoublewen** [comment]
Hi @jrobinso  -- I'd love to wire up the `locuschange` event to the URL, like the example you have here:
https://igv.org/web/release/2.0.0-rc3/examples/track-url.html

However, the example doesn't seem to work -- if you pass a different locus in the URL, it gets overwritten upon document load.  E.g. if you click on 
https://igv.org/web/release/2.0.0-rc3/examples/track-url.html#/locus/chr1:155,160,475-155,184,290 
...the browser will reset to chr1:155,160,475-155,184,2**82**.

I also notice that this example seems to have been dropped sometime after 2.0.0-rc3.  Is there a reason for its removal?

Sorry if I'm highjacking this issue, but my question seems related.  Also related to #526 ?

**Comment by jrobinso** [comment]
Sorry I'm not understanding what you are saying.   The locuschange event
reports locus changes back to the registered listener.   It has nothing to
do with the URL or query parameters.

The URL you list is not a valid syntax.    If you want to open IGV at a
specific locus use the "locus" query parameter, for example

https://igv.org/app?locus=chr1:155,160,475-155,184,290
<https://igv.org/web/release/2.0.0-rc3/examples/track-url.html#/locus/chr1:155,160,475-155,184,290>

**Comment by odoublewen** [comment]
Understood, thanks for the clarification.  The "locus" query parameter is what I want to use.  I'm also curious how this can be made to work with multiple browsers.  The query term is consumed by both browsers in this example:
http://igv.org/web/release/2.2.10/examples/multipleBrowsers.html?locus=chr20:100-200


By the way, the URL I pasted is coming directly from the examples on the igv.org website.  If you open:
https://igv.org/web/release/2.0.0-rc3/examples/track-url.html
...then the URL updates to:
https://igv.org/web/release/2.0.0-rc3/examples/track-url.html#/locus/chr1:155,160,475-155,184,282
Perhaps this is a defunct example -- seems likely since it was removed in later release directories?

**Comment by jrobinso** [comment]
That is not an official release, note the "rc3" qualifier,  I don't recall
details from then we experimented with different things.

If you mean you have multiple igv instances in the same page then yes, they
will all get the same parameters, the parameters are for the page.   There
isn't anything we can do about that.

**Comment by jrobinso** [comment]
Events are documented  https://github.com/igvteam/igv.js/wiki/Events
