### ISSUE TITLE
No feature found with name "<feature name>"

### ISSUE THREAD

**Issue by s-paquette** [igvteam/igv.js#374]
When attempting to view an HG38 BAM with a feature name as the locus (as opposed to chromosomal coordinates), we get the following error:
![image](https://user-images.githubusercontent.com/8442808/27409225-4afc9af8-5695-11e7-8b69-1d3e82e8283f.png)

This doesn't happen to HG19 BAMs; they find the locus without issue. We tested with the most recent release of IGV.JS, and these settings:
```
{
    "showNavigation": true,
    "genome": "hg38",
    "locus": "EGFR",
    "tracks": [{
        "sourceType": "gcs",
        "type": "bam",
        "url": gs://<BAM path>,
        "name": "<BAM name>",
        "withCredentials": true
    }, {
        "name": "Genes: Gencode v24",
        "url": "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz",
        "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz.tbi",
        "order": Number.MAX_VALUE,
        "displayMode": "EXPANDED",
        "format": "gtf"
    }],
    "withCredentials": true
}
```

I've tried a few others such as TP53 and TNN and gotten the same error for HG38, but not HG19. Additionally, the search doesn't seem to work with feature names either, just coordinates. Do we not have things set up right for HG38?

**Comment by jrobinso** [comment]
Hi,

The webservice we use currently supports only hg19.  I will look into
updating that, it shouldn't be too difficult.   In the meantime you can
provide your own webservice for feature name searching as described here:
https://github.com/igvteam/igv.js/wiki/Browser  ( see search object
description).

**Comment by jrobinso** [comment]
I'm adding hg38 to the search webservice, this should just start working
tomorrow morning sometime.   If its not working by mid day ping this issue
again.

On Wed, Jun 21, 2017 at 9:02 PM, James Robinson <jrobinso@broadinstitute.org

**Comment by s-paquette** [comment]
Thanks! That took care of it.
![image](https://user-images.githubusercontent.com/8442808/27453418-3ea5f0fe-574b-11e7-9ec1-4ee39355c4d9.png)

**Comment by IritReshef** [comment]
How can I use the search automatically from my fasta and gtf files? 
I am using genomes that are not hosted by IGV, and the search goes to hg19 - retrieving incorrect location.

**Comment by jrobinso** [comment]
Hi,

First the search should not go to hg19 unless you set a genome id = hg19.
Could you post your config?

To support a custom genome you have 2 options.

(1) setup a search webservice as described here (bottom of page):
https://github.com/igvteam/igv.js/wiki/Browser
(2) load a non-indexed bed or gtf with the "searchable" property set to
true,  see track type annotation here:
https://github.com/igvteam/igv.js/wiki/Tracks

**Comment by IritReshef** [comment]
Hi,
I tried this track:
{
            "name": "annotation",
            "displayMode": "EXPANDED",
            "url": "https://igv-bam-server.incpm.weizmann.ac.il/bio/db/gendb/Mus_musculus/Ensembl/GRCm38/annotation/82/Mus_musculus.GRCm38.82.sorted.gtf",
    "indexed": false,
    "searchable": true,

}
With no genome in the options or id in reference and it still goes to:  https://portals.broadinstitute.org/webservices/igv/locus?genome=hg19&name=prmd9
When I type in the search box.
I am trying to set a search service now, hopefully this will work

Any notes or insight are welcome,
Thanks,
Irit

**Comment by jrobinso** [comment]
Looking at this now.  That track is not reachable, could you make it
available to me?    Also, could you post your entire config section not
just the track.   I want to see how the reference is defined.

You didn't specify the release,  are you working on the latest code in
"master" or a release?

**Comment by IritReshef** [comment]
I can’t make the files reachable for you since it is an inside server.
I am using 1.0.8
Attached is the html file I am trying to run – again you cannot see the files themselves but you can see the configs.
This is different test sample but the gtf and fasta files are the same, just the number of samples is smaller.
The Final goal is to have a link to this html from our report (html file) to this html, opened in the right location (according to gene name)
Thanks,
Irit

**Comment by jrobinso** [comment]
Hi,   I don't see the html attachment.   Its not neccessary for me to see the html just the javascript section where you set up IGV, in particular the entire "config" object for the igv browser.

I realize I can't reach your server but could you zip and put the gtf file somewhere reachable, such as dropbox, or email it to igv-team (at) broadinstitute.org?

**Comment by IritReshef** [comment]
I created a temp folder with the html,  fasta, gtf and one example bam files
Try to reach it here:
https://owncloud.incpm.weizmann.ac.il/index.php/s/MBoJvHbg07eY6Li

**Comment by jrobinso** [comment]
Got it, but its still downloading.  I really didn't need the fasta.   If it finishes overnight I'll look at it tomorrow.

One observation, the gtf file is much too large to load into a browser without an index, its almost 1GB.  How much memory do you expect to be available in your user's web browser?   Also, how long do you expect them to wait until the track is loaded?  This does not look viable.    

For searching I suggest you grep out the gene records of interest and make a much smaller bed file with just the locations you want to search on.    This file should be on the order of 6-10 MB.   You can index and use the full gtf as another annotation file,  but don't use it for search.  I suggest using tabix to index.   

Alternatively you can use a web service.

**Comment by IritReshef** [comment]
OK
On the other hand, since I already configure a bam server, I am trying to builed on it a “search server” as well. I can permanently store my gtf files there…
I want to give it the gene name and the gtf file path and run a shell scipt that returns the right location. 2 questions about this:

a.       Do you have any example of a search page so I can try to do the same? Or maybe an advice of how to run a simple awk or awk-like code from a server or HTML ?

b.      What should I return in case no location was found? Empty response? Empty list?

**Comment by jrobinso** [comment]
Hi, the tar download finally completed.   I can't look at this until
Thursday,  but in the meantime I have started adding support for mouse
"mm10" to the search service.  When this completes you can use that by
specifying an id of "mm10" in your reference config (the id is blank now).
  Only of course if that's the assembly you are using.

WRT search service I can't give you any advice in implementing the
webservice, there are plenty of books and articles for that,  but if no
results are found return an empty json array.

**Comment by jrobinso** [comment]
I added mm10 to the search service, and an example file in the dev folder (mouse.html).    You don't have to use our fasta, you can still use the search for that assembly by setting the id field in the reference definition to "mm10".   

As an aside,  if not supplying optional parameters (e.g. the indexURL) just leave it out of the definition,  don't include it with an empty string as a value.    If you want the field shown for completeness or as a placeholder set the value to undefined, not an empty string.   These objects are not json they are objects.

I'm closing this because the issue was for hg38 searching specifically and has gotten pretty far afield.  If you have further problems open a new issue.
