### ISSUE TITLE
bigWig Example

### ISSUE THREAD

**Issue by datbdude** [igvteam/igv.js#387]
The 'encode bigWig' track in examples/api.html throws the error:

> Error accessing resource: http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k4me3StdSig.bigWig Status: 0

If I am understanding correctly, bigWig files are also accessed using byte range requests. When I am serving bigWigs via S3 and other forms of hosting, the whole file is being requested with a HTTP 200 code.

**Comment by jrobinso** [comment]
Thanks for the report, the problem was a mixed http / https mode request.  Our server now apparently redirects http to https,  and the UCSC server for the encode data supports only http.   This is a recent problem.   I fixed it by copying the bigwig to our s3 servers, it should work now.   If it doesn't clear you cache to force a page reload.

Yes,  bigwigs use range-byte requests.  If you are only seeing http 200 codes there is a server problem.   Load the  Encode bigwig from the examples/api.html and examine request headers & response in developer tools.   There will be an "options" request which is 200,  all the gets should return 206.

**Comment by datbdude** [comment]
I am serving the bigWig files from s3 using the same CORS configuration as in the wiki. Are there additional configurations I may have missed?

**Comment by datbdude** [comment]
It turns out, this only happens when I explicitly set the format option to 'wig'. Removing this option results in the api behaving as expected.

**Comment by jrobinso** [comment]
That makes sense since the format is not wig.   The track type is wig,  but format refers to the file format.  The purpose of that field is to specify a format for files with non-standard extensions.   You normally don't need to use it.
