### ISSUE TITLE
Add locus coordinates to URL

### ISSUE THREAD

**Issue by arq5x** [igvteam/igv.js#500]
As a feature request, would it be possible to add specific coordinates as a parameter to the URL so that one can share a link taking a user to an exact location?

For example: https://s3.us-east-2.amazonaws.com/ccrs/ccr.html/locus/chr20-62075858-62076005

Is this possible?

**Comment by jrobinso** [comment]
Hi Aaron,

This isn't announced or documented because I'm still working on it,  but
this should already work as a parameter.   You need to % encode the locus.
 Try this

http://igv.org/web/test/test.html?locus=myc


Also,  IGV XML style sessions are mostly supported.   See the example
url below.

http://localhost/igv-web/dev/igvjs.html?igvSessionXML=..%2Ftest.xml&locus=15%3A63%2C588%2C066-72%2C426%2C258

The XML sessison format will be replaced with json,  but the idea here is
to have an "empty" igv.js page and populate it with sessions from links to
session files.   This would be more flexible than the current setup.  As I
said this is work-in-progress.

**Comment by jimhavrilla** [comment]
Hey Jim we already have a working solution to this, but I had a question that maybe you can answer for me...where does the locus attribute get stored (seems like it isn't in the igvDiv object) when someone enters a new locus into the search bar?  Because if I can get that information I can solve another issue we have which is updating the URL to reflect a new search.

**Comment by jrobinso** [comment]
The short answer is it doesn't get stored.     There is no API for this,
please open another issue describing what you want to do.   Its not a good
idea to build systems based on internal state as this can and will change
without warning.

Jim

**Comment by jimhavrilla** [comment]
Will do.  Thanks.
