### ISSUE TITLE
BAM Track Empty

### ISSUE THREAD

**Issue by hakanEdico** [igvteam/igv.js#515]
I am implementing igv.js in an internal company website and am having some problems with displaying the BAM. 

The BAM file and the viewer are on the same domain, lets call it http://testing.com 

The webpage is http://testing.com/cgi-bin/script.pl?invocation_id=33947&exec_id=1
The BAM file is accessible at 
http://testing.com//mnt/suite_logs/33947/suite_def/Hakan_Test/EId1/SRA056922_hs37d5.bam

The file is 100% accessible by the webpage. No CORS or anything required as it is the same origin. 

Looking at the network debugger on my browser, a request is made for the hg19 fasta/fai files which I have included, however no request is even being made for the BAM file. Similarly when I change the locus, no request is made for the BAM. Its not that the file isn't accessible, it's not even being accessed! 

I am using the beta build of igv.js 

EDIT: I was able to see a request for the BAM when I searched for chrM in the viewer. However this returned an error: 
BAM header contains an invalid BAM magic 

No other chrm makes a request for the BAM. Using samtools I see there are reads in all chromosomes.

EDIT 2: I have tried with different BAM files and I am able to view chrM without the BAM header error. So there are two issues - one is no matter that BAM I use I am only able to query for chrM, any other chromosome does not request the BAM (track is empty). The other issue is, for the initial BAM I was using we add in some additional information in the header and I guess igv does not like this. The extra header fields begin with "@PG   ..."

**Comment by jrobinso** [comment]
A couple of suggestions, but  I  would need to see your config to really
offer any advice,   (1) are you zoomed in enough to see alignments?
 Nothing is loaded from the bam file until you are sufficiently zoomed in,
I don't recall the default (this is configurable)  but 1kb should be plenty
zoomed in,  (2) are your sure the sequence names in bam and fasta are the
same.

**Comment by hakanEdico** [comment]
I am able to view BAM tracks now if I zoom in enough (generic BAM file) 

However, I still get the "BAM header contains an invalid BAM magic" error on all of my BAM files. What is the source of this error? Cannot find it.

**Comment by jrobinso** [comment]
I'm not sure what you mean by "source if the error",  ultimately whatever created the .bam files.  The first 4 bytes of the file should be "BAM\1" (from the spec).    This is checked if if the magic # is anything else an error is logged.   Its somewhat suprising that the magic number can be wrong, but the file otherwise works.

**Comment by hakanEdico** [comment]
I see that the file does indeed start with BAM\1 

First 4 bytes: 
42 41 4d 01

**Comment by jrobinso** [comment]
If you can share one of your bam files with me I'll look into it.
Otherwise, if you want to yourself the code that checks it is here, line
80:   https://github.com/igvteam/igv.js/blob/master/js/bam/bamUtils.js

**Comment by hakanEdico** [comment]
Looking at this code in a debugger: 

unc = igv.unbgzf(compressedBuffer);
uncba = new Uint8Array(unc);\n
header = igv.BamUtils.decodeBamHeader(uncba, genome);

I see compressedBuffer has length 14512. 
After the function call, unc has bytelength of 0, uncba is undefined, so when the magic is calculated it comes out to 0. I will trim this BAM (its 82GB) and share with you. Is just the header enough or should I keep some reads as well?

**Comment by jrobinso** [comment]
Just the header should be enough,  but it needs to be a proper bam file so
maybe it needs a few reads.   After trimming you still have the problem
with the trimmed file.   This is rather curious.

**Comment by jrobinso** [comment]
Meant to say "after trimming confirm you still have the problem with the
trimmed file"

On Wed, Jan 10, 2018 at 3:03 PM, James Robinson <jrobinso@broadinstitute.org

**Comment by hakanEdico** [comment]
Used samtools to keep the header and only keep part of chromosome 1, same error. 

Need to get some proprietary information out of the header then will share along with the BAI.

**Comment by hakanEdico** [comment]
[bam.zip](https://github.com/igvteam/igv.js/files/1620758/bam.zip)

**Comment by jrobinso** [comment]
Unfortunately, I can't reproduce the error with the bam you sent.   The compressed size is 43,430 bytes,  uncompressed is 146,158 bytes,  and the magic number is as expected.   I assumed but did not confirm that your server supports range-byte requests.   If it doesn't you could get all sorts of weird behavior.

**Comment by hakanEdico** [comment]
Thanks for trying. Did some more digging yesterday and have found out partially why some BAM files work and some don't. 

As you noticed, my BAM file was compressed, as are most. When requesting a BAM file example I found online, looking at the http headers returned I see that the content type is binary/octet-stream and a file format is not given. Looking at this in an application like postman, I see that all binary is returned. 

When I request the BAM that has been causing me problems, the server returns content-type as gzip. Once again looking in postman, the result is automatically uncompressed! You can read the header in plain text and even the rest of the BAM is decompressed. When I request the same BAM with a header: accept-encoding: none (or blank), then it is not auto decompressed and the binary file is returned. 

Looking at the code in igv, it looks like it assumes that it is gzipped. 

// Uncompress data,  assumed to be series of bgzipped blocks
// Code is based heavily on bam.js, part of the Dalliance Genome Explorer,  (c) Thomas Down 2006-2001.
igv.unbgzf = function (data, lim) {

And that function is called by the readHeader function which passes it to the decodeBamHeader function  to check the BAM magic. So does IGV always assume compressed? 

The thought was to include the accept-encoding header in the XMLHTTPRequest object you make, but turns out that is prohibited! So at this point I either have to configure my server to not return content type gzip, or find some workaround in IGV. Let me know what you think.

**Comment by jrobinso** [comment]
Ahh yes,  good digging!   I now recall a problem like that on an Apache
server,  the server incorrectly returned the content-type gzip header.   I
actually wrote about it here (scroll to bottom):
https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.    As you
point out if that header is set the browser gunzips it,  you can't control
that.   The fix was to explicitly add the the content-type setting for
".bam" files to binary-octet-stream in the apache config.

This is a server-side error,  in my opinion,  the content-type gzip should
never be returned for a bam file.

Most Apache servers do not do this,  I don't know what conditions cause the
problem.

**Comment by hakanEdico** [comment]
Alright I changed my Apache server config to return octet-stream for .bam extensions and viola! Thanks for your all of your help!

**Comment by jrobinso** [comment]
If you can figure out why Apache was doing that I'll update the wiki,  I
could not,  probably not worth the time to find out.

**Comment by hakanEdico** [comment]
Yeah at this point I'm just happy it works. There was no type specified for .bam extensions. I don't know why it would auto unzip, pretty crazy behavior.

**Comment by jrobinso** [comment]
All bam files are gzipped, actually bgzipped,  that's part of the format.
I suspect apache is looking at the header and discovering it is gzipped,
then adding the content-type header.    This causes the browser to gunzip
the response before javascript even sees it.     You can't recover from
this even if you detect it,  when the bam file is gunzipped none of the
index pointers are valid,  and there is no way to put it back together.

I could probably add a check to at least catch the error and report it to
the console since this has now happened on at least 1 other Apache server.
 Again most Apache servers do not do this.

Glad its resolved,  leave this open as a reminder to add the check.

**Comment by hakanEdico** [comment]
Yeah I agree that some error handling would be appropriate. It would save any future users the trouble of digging to find what happened. Thanks again for the help!
