### ISSUE TITLE
Support datasets with large #s of rows

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#792]
Currently igv.js creates a canvas  ~ (flanking*screenwidth*rowCount).   Some datasets, such as deep coverage alignments and copy number,  can have a large number of rows resulting in a huge canvas.

To support these we need to create a vertical tiling scheme and draw canvas tiles on demand as they scroll into view.

Max sizes from quick web search

- For Google Chrome, the maximum allowable width and height are 32,767 pixels and the maximum allowable area is 268,435,456 pixels.
- 
- For Firefox, the maximum allowable width and height are 32,767 pixels and the maximum allowable area is 472,907,776 pixels.
- 
-  For IE, the maximum allowable width and height are 8,192 pixels.
- 
-  For IE Mobile, the maximum allowable width and height are 4,096 pixels.

**Comment by ggydush** [comment]
Hi @jrobinso, I was wondering if this is actively being worked on or if the canvas size limits will always prevent handling large numbers of rows in an alignment track.

Most of the BAMs I'm interested in have ~1,000-10,000X depth and have very low allele fractions. To compensate, I've been splitting BAMs into an ALT bam and a NON_ALT BAM and loading each as separate tracks to ensure the ALT reads are always sampled. It would be awesome if we wouldn't have to do that, but I know this issue is complicated and not all users will be working with such high depths.

**Comment by jrobinso** [comment]
Hi @ggydush yes I do plan to redesign the way we use canvas to overcome these limits.   Its also important for general performance and memory management.   As you say its complicated.     Thanks for bumping this issue,  and do it again periodically if its not fixed.

**Comment by jrobinso** [comment]
@ggydush and others, this has been fixed several releases ago, the new implementation only creates a canvas for what's in view +/- 1 screen.  There should be no alignment depth restrictions.  I have tested on a bam with depth on the order of ~10,000
