### ISSUE TITLE
Region of interest for igv.js

### ISSUE THREAD

**Issue by fany3** [igvteam/igv.js#854]
Is it possible to add ability to highlight ROI (across one track for each genotype)  ?
Thank you!

**Comment by jrobinso** [comment]
Not currently.  What is the use case / motivation for this?

**Comment by oleraj** [comment]
We want to highlight low coverage regions in coding regions for specific individuals.  For example, if we have a trio, and only one individual shows low coverage for a coding exon, this ROI would show up in that individual's BAM track but not the others.  Having a colored ROI can make it easier for our users to see whether a gene is "well-covered" or whether they might want to fill-in with Sanger sequencing to be sure there are no coding variants in the gene.  Having individual-specific ROIs could help the user quickly assess which individual is missing coverage.

**Comment by jrobinso** [comment]
OK, got it.   In the meantime you could load bed tracks to mark these regions as a temporary solution.   I didn't envision ROI overlays being used with bam tracks,  what color and transparency have you tried?

**Comment by oleraj** [comment]
Agreed we could load a bed track to mark the region for now.  We're using red right now, though not sure the transparency level.  (@fany3 would know.)  Here's an example of what we have so far, loading a bed file for each individual.  It appears to be doubling the intensity if two individuals have low coverage for part of the region.  For example, I think the BAM file second from the bottom is low coverage for the entire highlighted region and another BAM file is low coverage for only a part of the intron (we are looking at coding + 8bp into the intron from either side), so that part is darker.
![image](https://user-images.githubusercontent.com/10860409/52377708-ac10ed80-2a33-11e9-8ccc-a9da525a95e8.png)
Again, for our purposes it would seem cleaner if the coloring was specific to one track, especially when the coverage scale is small it can be difficult to tell at a glance which sample is the low coverage one.

**Comment by jrobinso** [comment]
OK, the pic is helpful.   This shouldn't be too difficult but I haven't looked at the code in detail yet.
