### ISSUE TITLE
Feature request: Keyboard shortcuts for jumping between variants/features

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#884]
In desktop IGV, you can use the CTRL-F and CTRL-B keys to jump to the next/previous variant in a VCF file or feature (in a BED file for example). Similar shortcuts have been requested for igv.js

Note: there is also a IGV desktop feature request to include an option to skip VCF variants that did not pass the filtering threshold. See [IGV issue #638](https://github.com/igvteam/igv/issues/638) That should also be implemented in igv.js.

**Comment by brentp** [comment]
related to this, is there an API for accessing the variants in a VCF track? or records in a BED track?

**Comment by jrobinso** [comment]
@brentp Could you expand on what you mean?  Obviously the vcf and bed track files are available to the app that has embedded IGV,  these records aren't created by igv.

**Comment by brentp** [comment]
maybe in cases where the entire VCF or BED was read in (no index), then it would be possible to have an API in igv.js that let's the user know the index of the current record (variant or bed region) and then to access the chrom, start, end of a region based on the index

**Comment by jrobinso** [comment]
@brentp I'm still not following the use case but you can always get the current region in view with [browser.currentLoci](https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#currentloci),  or get a clicked object with events.  In any event this is not related to the issue opened here.

**Comment by kkapuria3** [comment]
In numerous cases, I have to cycle through scarce features in bed/gff3 file spread across whole human genome. Using the hotkey feature (Ctrl-F/Ctrl-B) in IGV desktop app, helps me save time navigating tracks quickly. I just select the relevant track and use hotkeys to cycle through them. 

It would be really helpful if this feature is added to IGV web. 

Also, since its been a while since this issue was open, is there a similar function (i.e. click on track to view features in a pop-up list and then click individual elements to skip to them) that is already implemented. 

Thank you !

**Comment by jrobinso** [comment]
Hot keys in igv.js are difficult for a number of reasons, but your idea of a popup for navigation is promising.    I have a full plate at the moment, actually always, so I can't give an ETA on this.   A pull request would be considered.

**Comment by jrobinso** [comment]
Update, I'm working on this now,  implemented as hot keys like the desktop.

**Comment by kkapuria3** [comment]
Thank you for this ! This feature is amazing ! Kudos to you !!
