### ISSUE TITLE
Customize labels for BED track

### ISSUE THREAD

**Issue by oleraj** [igvteam/igv.js#939]
Hi,

I'm interested to know how we can add additional labels in the pop-over for a BED track.  Is it as simple as adding an additional column in our BED file?  

To see what options are available, I tried to look at your example [here](https://igv.org/web/release/2.2.14/examples/multi-locus.html) but it's not loading properly. 
![image](https://user-images.githubusercontent.com/10860409/61545721-1cc22a00-aa16-11e9-8f39-031f26ffda5d.png)
 
One of the main things I would like to do is add an additional label for the region so that in the "all" view the user can see what chromosome the region is on and how large it is, which is more difficult to tell for the smaller chromosomes.  This is what we have in the popup right now, following regular BED file format:
![image](https://user-images.githubusercontent.com/10860409/61545869-70347800-aa16-11e9-9efc-1236261d48d2.png)

If you have any advice for adding custom columns to the BED track (and removing some of the labels from the pop-over that are not needed, e.g., cdsStart) that would be helpful.

Thanks!

Andrew

**Comment by jrobinso** [comment]
Hi, thanks for the report.    The example fails because the underlying file has been moved,  I am fixing it, but that would not help you in any event.   There are no customization options for bed files per say without writing custom javascript and using an event handler.    You can see https://igv.org/web/release/2.2.14/examples/custom-track-popover.html  for an example.   I'm not sure how helpful this is.   BED customization is desirable its just not supported yet.

RE the chr "all" problem.   That is a bug,  it should display the real chromosome and coordinates there.  I will fix that.

**Comment by jrobinso** [comment]
Sorry for the delay, the chr position problem has been fixed (it displays actual coordinates now).
